= Elm, Elixir and Phoenix: Not a How To Guide
:author: Sashan Govender
:cpp: C++

Having a background in {cpp} development mainly working with low-level network protocols and designing
network appliances, trying to do web programming with modern frameworks is undoubtedly foreign
territory. I jumped into it by learning Elixir, primarily as a language over the past year (2017)
without dabbling in the surrounding infrastructure like OTP or Phoenix. At this level, when just
playing with the core language, idioms from {cpp} carry over making it straightforward for me to think
things like 'Oh that part is like {cpp} feature X except with some differences'. Basically it was easy
to see what the analogous feature in Elixir was, and which features didn't carry over, of which
there are many, since {cpp} is such a large language these days. However, just mucking around with the
language isn't all that practical and I want wanting to escalate things and build a web site so I
picked up Phoenix, the Elixir web development platform. It's what Rails is to Ruby. I was hoping
some of the development process from {cpp} work on Linux would translate over, but in terms of the
framework not much does. It doesn't look like people use make, cmake or autotools in the web
development world. Dependencies are managed per project by this thing called Node Package Manager
and they don't seem to rely on the distributions package manager much. Additionally there's this
concept of front-end and back-end that doesn't exist in my world. From a {cpp} programmer's
perspective it's all the same. In this case back-end development meant the Elixir Phoenix framework,
the stuff that runs on the server. Front-end is the stuff running in the browser. Typically this is
HTML or JavaScript, neither of which I'm a fan of programming in. So I looked around and saw Elm
which is similar to OCaml/F#, languages I know, so I latched on to that, happy to find a statically
typed language for web front end development, and decided to use it instead raw JS or HTML.


Thus my tasks became:

- Get Phoenix application setup.
- Use Elm to generate the JavaScript.
- Somehow integrate these 2 things.
- Start Phoenix.
- Point my browser to the landing page and see 'Hello World!'.

Working through this it felt a lot like the days of Win32 programming when you would go through
Petzold's book to look up the boilerplate code to, for example, get a handle to the GDI so you could
draw a circle on the screen. Now the only thing that's changed is that instead of a book, you
DuckDuckGo the web and reap the top 5 hits to some random person's blog and pull down some code they
copied and pasted from the some other website and hope that it works. And often it does, and that's
good, because after all the boilerplate code isn't really interesting code. It's not the
application, it's not the business logic, it's not the stuff that's doing anything interesting. It's
just the boring shit that needs to be there so you can write 'Hello World!' on your landing page.

Pretty straightforward. Except when the boilerplate code doesn't work. Then it's a pain the arse.
First set of instructions I grabbed from some post on Medium. No luck there. Another post from
another website. Nope no luck there. A few days spent fiddling with the `package.json` config files
(which one, there were many?) trying to resolve things on my own. No luck. rm -rf the project and
start again. Try the first set of instructions and still no luck. Still not getting any JavaScript
from the Elm program. Manually compile the Elm program to JS. Still no luck.

So how to resolve this? I had to take a step back and ask myself 'what would I do in a similar
situation if trying to resolve an issue with C++ and a library I was trying to use?' The only answer
I could come up with is 'understand the bits and pieces and how they interact better'. So I took a
step back, ignored all the blog posts claiming to have instructions about how get Phoenix up and
running with Elm and dug into the Phoenix directory structure to learn more about what the different
directories represented. What the hell is the `assets` directory? What's `priv`? What's `deps`? Why
is there no `web` directory that all these instructions refer to? Which of these directories and
files should I keep in git because they are source code and which should I ignore because they are
generated? In answering these questions I realized that the Phoenix 1.3 had made some backward
incompatible changes. Instructions setup to work with Phoenix less 1.3 would not work with 1.3 since
the directory layout changed. It was only after learning more about how the framework worked that I
was able to resolve it and create a website that would, as part of the `mix` process, turn the Elm
code into JavaScript and have it ready for delivery to the client.

So what's the point of this post? Like the title says, it's not a `How To` guide. It's a reminder
that sometimes what looks like a shortcut, like following some setup instructions from a web page,
may not be a shortcut. Knowing more about the tools you're trying to use, the frameworks, and
libraries is always going to be beneficial, and is the only way to solve a problem when you've
exhausted the set of instructions that are out there. Stepping back from the problem, and asking it
questions, instead of bloody mindedly typing random crap into config files hoping that it will
magically work, is often better.

Written in link:http://www.methods.co.nz/asciidoc/[Asciidoc] using link:http://www.vim.org/[Vim].
