No Debugging Programming in Elixir
==================================
Sashan Govender

At last I have found a language that I do not need to debug. I can just write the code and have it
run on the input data, and it will give me the correct result. The language is
link:Elixir[elixir-lang.org]. This is the Holy Grail!

So this is what happened. I'm studying algorithms and doing a course and one of the assignments was
to write a inversion counter. So what's an inversion? It's basically where, in a list of numbers, a
number is out of sequence with respect to another number in the list.

.Example of no inversions
.......................
[1,2,3,4]
.......................

.Example of inversion. Here 3 is out of order.
.......................
[1,3,2,4]
.......................

.Here there are 6 inversions.
.......................
[4,3,2,1]
.......................

A brute force algorithm that calculates this would have check each number against all the numbers in
the list and therefore would be `O(n^2)` which is inefficient. The trick is to piggyback on
mergesort which has a running time of `O(nlogn)`. The reason this works is because during the merge
step of the mergesort we detect inversions. When writing the larger array from the two
subarrays the process 'detects' inversions every time you find an element in the left array that is
larger than one in the right array. At the end of the day a few subtle modifications to the
mergesort algorithm is all that's needed. And that's what I did in Elixir. I stumbled along and
my tired fingers and sore eyes cranked out some Elixir. The biggest surprise was it worked
(ignoring compilation errors) right from the start. I didn't have an input case that produced the
wrong answer for the assignment. I didn't have to go back and rewrite any of the pattern matches. I
didn't have to fix the recursion because I'd put the calls in the right place. Here it is.

++++
<script src="https://gist.github.com/sashang/91ead48d2a5c51103279600c8759112b.js"></script>
++++

The problem with the solution above is it is slow. On an input set of 100000 numbers it took 30
seconds to compute. It contains a 'hidden' operation that makes the summarize function `O(n^2)`. The
'hidden' operation is the `++` that appends the element to the end of the list. To do this it has to
walk to the end of the list, which is an `O(n)` operation thus turning the `summarize` function from
an `O(n)` operation to an `O(n^2)` function. The way to fix it is to prepend the head on the list
and then reverse the list later as shown below.

++++
<script src="https://gist.github.com/sashang/f8654ed2f08560b183f6971f7d6dc872.js"></script>
++++

